title: Shashi's Blog
description: "A list of articles written by Shashi Kant."
# baseurl: "/blog"
url: "https://shashikg.github.io/blog"

paginate: 1
paginate_path: "/blog/page:num/"
plugins: [jekyll-paginate]

markdown: kramdown
highlighter: rouge

social-accounts:
  facebook: "shashikg.iitk"
  twitter: "shashikg_iitk"
  youtube: "UCD1ELtVIfZnmIGbfVT9bHXQ"
  googleplus: "101058871085746328098"
  github: "shashikg"

sass:
  sass_dir: _sass
  style: :compressed

# google_analytics:
# disqus_shortname:
